

CREATE DATABASE FRIZERSKI_SALON
GO
USE FRIZERSKI_SALON

CREATE TABLE STANICE
(STANICA_BR INT IDENTITY (1, 1)  PRIMARY KEY,
NAZIV_STANICE VARCHAR (20)
)
CREATE TABLE ZAPOSLENICI
(ID_ZAPOSLENIKA   INT IDENTITY (1, 1) CONSTRAINT PK_ZAPOSLENIK_ID PRIMARY KEY,
IME VARCHAR (20) NOT NULL,
PREZIME VARCHAR (40) NOT NULL,
OIB NVARCHAR(13) ,
ADRESA VARCHAR(MAX),
MOBITEL NVARCHAR(20),
STANICA_BR INT  CONSTRAINT FK_STANICA FOREIGN KEY REFERENCES
STANICE(STANICA_BR) UNIQUE NOT NULL
)
CREATE TABLE KATEGORIJE
(KATEGORIJA_ID INT PRIMARY KEY ,
DULJINA_KOSE  VARCHAR(20) NOT NULL
)
CREATE TABLE USLUGE
( ID_USLUGA INT  CONSTRAINT PK_USLUGA_ID PRIMARY KEY,
NAZIV VARCHAR (MAX) NOT NULL,
TRAJANJE_MIN INT,
CIJENA DECIMAL (5,2) NOT NULL,
ID_ZAPOSLENIKA INT CONSTRAINT FLK_ZAPOSLENIK_ID  FOREIGN KEY REFERENCES
ZAPOSLENICI (ID_ZAPOSLENIKA) NOT NULL,
KATEGORIJA_ID INT FOREIGN KEY REFERENCES KATEGORIJE (KATEGORIJA_ID)
)

CREATE TABLE KUPCI
(ID_KUPCA INT IDENTITY (1, 1) CONSTRAINT PK_KUPAC_ID PRIMARY KEY,
IME VARCHAR (20) NOT NULL,
PREZIME VARCHAR (40) NOT NULL,
MOBITEL NVARCHAR(20),
DATUM_RODJENJA DATE )

CREATE TABLE REZERVACIJE
(REZERVACIJA_BR INT  IDENTITY (1, 1) PRIMARY KEY,
KUPAC_ID INT CONSTRAINT FK_KUPAC_ID FOREIGN KEY REFERENCES KUPCI (ID_KUPCA) NOT NULL,
DATUM DATE NOT NULL,
VRIJEME TIME(0) NOT NULL )

CREATE TABLE EVIDENCIJA_RACUNA
(RACUN_ID INT IDENTITY(1, 1) CONSTRAINT PK_BR_RAČUNA PRIMARY KEY,
KUPAC_ID INT CONSTRAINT FK_KUPACID FOREIGN KEY REFERENCES KUPCI (ID_KUPCA) NOT NULL,
USLUGA_ID INT  CONSTRAINT FK_USLUGA_ID FOREIGN KEY REFERENCES USLUGE (ID_USLUGA) NOT NULL,
CIJENA DECIMAL (5,2) NOT NULL,
STANICA_BR INT FOREIGN KEY REFERENCES STANICE(STANICA_BR) NOT NULL)



