CREATE PROC UPDATE_ZAPOSLENIK
@IME VARCHAR(20),
@PREZIME VARCHAR(40),
@OIB VARCHAR(13),
@ADRESA VARCHAR(MAX),
@MOBITEL NVARCHAR (20),
@STANICA_BR INT
AS
UPDATE  ZAPOSLENICI
SET IME = @IME,
PREZIME = @PREZIME,
OIB = @OIB,
ADRESA = @ADRESA,
MOBITEL = @MOBITEL
WHERE
STANICA_BR=@STANICA_BR
