CREATE PROC PREGLED_ZAPOSLENICI
@STANICA INT
AS
SELECT IME,PREZIME,SUM(CIJENA) AS UKUPNO
FROM ZAPOSLENICI
JOIN
EVIDENCIJA_RACUNA ON
ZAPOSLENICI.STANICA_BR = EVIDENCIJA_RACUNA.STANICA_BR
WHERE EVIDENCIJA_RACUNA.STANICA_BR= @STANICA
GROUP BY IME,PREZIME
GO
